# yet another python formatter
repos:
- repo: https://github.com/google/yapf
  rev: v0.40.2
  hooks:
  - id: yapf
    language: system

# prospector: collection of linters
- repo: https://github.com/guykisel/prospector-mirror
  rev: 7ff847e779347033ebbd9e3b88279e7f3a998b45
  hooks:
  - id: prospector
    language: system
    types: [file, python]
