version: '2'

services:
  bokeh:
    restart: always
    build: .
    image: discover-tc-applicability:master
    command: ["/opt/serve-app.sh"]
    environment:
      PYTHONPATH: '/project'
      SHELL: '/bin/bash'

    volumes:
     - './data:/project/discover-tc-applicability/data'
    ports:
      - '3251:5006'
